### ISSUE TITLE
numerical precision

### ISSUE THREAD

**Issue by soloice** [feizc/DiT-MoE#4]
Thanks for your nice work! What's the numerical precision used during training? I didn't find it in the paper. Is it bf16, fp16 or fp32? Or some mixed precision approach?

**Comment by feizc** [comment]
Hi, I'm very sorry for missing important information. 
We training XL and G version for FP16 and others are used FP32. 
It can also be checked in the sample.py in [line](https://github.com/feizc/DiT-MoE/blob/main/sample.py#L34).

**Comment by soloice** [comment]
Thanks for the information!
